// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notes.Persistance;

namespace Notes.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250113191018_InitialSeedData")]
    partial class InitialSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Notes.Domain.Car.Body", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bodies");
                });

            modelBuilder.Entity("Notes.Domain.Car.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoxType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("Notes.Domain.Car.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Notes.Domain.Car.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BodyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BoxId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrandId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarColorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarColorId1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SteeringWheelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SteeringWheelId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BodyId");

                    b.HasIndex("BoxId");

                    b.HasIndex("BoxId1");

                    b.HasIndex("BrandId");

                    b.HasIndex("BrandId1");

                    b.HasIndex("CarColorId");

                    b.HasIndex("CarColorId1");

                    b.HasIndex("SteeringWheelId");

                    b.HasIndex("SteeringWheelId1");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Notes.Domain.Car.CarColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarColors");
                });

            modelBuilder.Entity("Notes.Domain.Car.CarImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");
                });

            modelBuilder.Entity("Notes.Domain.Car.SteeringWheel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SteeringWheelType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SteeringWheels");
                });

            modelBuilder.Entity("Notes.Domain.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Notes.Domain.Car.Car", b =>
                {
                    b.HasOne("Notes.Domain.Car.Body", null)
                        .WithMany("Cars")
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Notes.Domain.Car.Box", null)
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notes.Domain.Car.Box", null)
                        .WithMany("Cars")
                        .HasForeignKey("BoxId1");

                    b.HasOne("Notes.Domain.Car.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notes.Domain.Car.Brand", null)
                        .WithMany("Cars")
                        .HasForeignKey("BrandId1");

                    b.HasOne("Notes.Domain.Car.CarColor", null)
                        .WithMany()
                        .HasForeignKey("CarColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notes.Domain.Car.CarColor", null)
                        .WithMany("Cars")
                        .HasForeignKey("CarColorId1");

                    b.HasOne("Notes.Domain.Car.SteeringWheel", null)
                        .WithMany()
                        .HasForeignKey("SteeringWheelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notes.Domain.Car.SteeringWheel", null)
                        .WithMany("Cars")
                        .HasForeignKey("SteeringWheelId1");
                });

            modelBuilder.Entity("Notes.Domain.Car.CarImage", b =>
                {
                    b.HasOne("Notes.Domain.Car.Car", "Car")
                        .WithMany("Images")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Notes.Domain.Car.Body", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Notes.Domain.Car.Box", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Notes.Domain.Car.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Notes.Domain.Car.Car", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Notes.Domain.Car.CarColor", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Notes.Domain.Car.SteeringWheel", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
